### ISSUE TITLE
Running from Visual Studio Task Runner Fails

### ISSUE THREAD

**Issue by bjones-autosoft** [keithmorris/gulp-nunit-runner#13]
Running the gulp task from the visual studio task runner fails with the exception:
```
Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:673:17)
    at run (node_modules\gulp-nunit-runner\index.js:125:18)
    at Stream.end (node_modules\gulp-nunit-runner\index.js:35:3)
```
Seems the trouble is that the visual studio task runner doesn't support stdin, so the following line fails.

``` javascript
	opts = {
		stdio: [process.stdin, process.stdout, process.stderr, 'pipe']
	};
```
I was able to work around the issue by changing it to
``` javascript
	opts = {
		stdio: [null, process.stdout, process.stderr, 'pipe']
	};
```
Not sure if this is a viable solution, but maybe since I don't think the runner would need to support input.

**Comment by keithmorris** [comment]
@bjones-autosoft ,

I updated as  you suggested. I was not able to test it in VS so please let me know if that resolves your problem. The fix is in release 0.5.1
