### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by dbones** [keithmorris/gulp-nunit-runner#20]
I notice you support the switches with mono. I gave this a quick run and i think you may need to execute mono directly.

exe which is run needs to be mono, 
(https://github.com/keithmorris/gulp-nunit-runner/blob/develop/lib/index.js#L140) 

and the location of the nunit runner will become a parameter.

**Comment by keithmorris** [comment]
I'm not 100% crazy about having the `mono` string hard coded in there.  I'd rather a "runtime" option that could be passed in but I think this will do in the short term.
