### ISSUE TITLE
Options of type 'number' are ignored

### ISSUE THREAD

**Issue by alexmaris** [keithmorris/gulp-nunit-runner#25]
It looks like the `parseSwitches()` function is ignoring options passed in as number types. For example, in the options specified below, the number of _workers_ is not passed through as an argument (it works if passed through as a string).

``` javascript
nunit({
    executable: 'nunit3-console.exe',
    options: {
        workers: 3,
        framework: 'net-4.5',
        teamcity: true,
        test: namespaces,

    }
})
```

**Comment by keithmorris** [comment]
Fixed via pull request #24
